### ISSUE TITLE
Info about error responses from Viagogo API

### ISSUE THREAD

**Issue by emsoaldin** [viagogo/viagogo-api-docs#4]
Hello,

I've successfully integrated Viagogo API into application, but I have question regarding error codes.

Here is the example of `validation_failed` response:

```
{
    "code": "validation_failed",
    "message": null,
    "errors": {
        "seller_listing.event.name": [
            "'name' must not be empty."
        ],
        "seller_listing.event.start_date": [
            "'start_date' must not be empty."
        ]
    }
}
```
So my question is, will there ever be more than one item in this array of error keys? Eg. Can `seller_listing.event.name` or any other contain more than one error inside of that array? I really can't reproduce scenario where key will have **more than one** item in array.

Also @akilburge sorry if this repo isn't for this type of question.
Thanks!

**Comment by akilburge** [comment]
@emsoaldin no problem. 

> Can seller_listing.event.name or any other contain more than one error inside of that array?

It's definitely possible to have more than one error in these arrays but the majority of scenarios will only have one.

**Comment by craigbarrett** [comment]
@emsoaldin how did you get access to the Viagogo API?
